/**
 * SynTract Native Build Pipeline™ — Core Types
 *
 * All build providers implement the BuildProvider interface. The pipeline
 * orchestrator only ever calls these methods, keeping provider logic fully
 * encapsulated and swappable at runtime.
 */

export type Platform = 'ios' | 'android' | 'web';

export type BuildStatus =
  | 'queued'
  | 'running'
  | 'success'
  | 'failed'
  | 'cancelled';

export interface FileManifest {
  /** Raw FILE_MANIFEST JSON extracted from a SynTract build result */
  files: Record<string, string>;
  entryPoint?: string;
  framework?: 'react-native' | 'expo' | 'capacitor' | 'web' | 'unknown';
}

export interface BuildConfig {
  /** Unique job ID (generated by the pipeline, passed to the provider) */
  jobId: string;
  /** Which platforms to build for */
  platforms: Platform[];
  /** Provider-specific options (signing, env vars, etc.) */
  providerOptions?: Record<string, unknown>;
  /** User ID who triggered the build */
  userId: string;
}

export interface BuildJob {
  /** Provider-assigned external job ID */
  externalId: string;
  /** Internal SynTract job ID */
  jobId: string;
  /** Provider that owns this job */
  provider: string;
  /** Platforms being built */
  platforms: Platform[];
  /** Current status */
  status: BuildStatus;
  /** ISO timestamp when submitted */
  submittedAt: string;
  /** Provider-specific metadata (build URL, workflow run ID, etc.) */
  meta?: Record<string, unknown>;
}

export interface BuildStatusResult {
  jobId: string;
  externalId: string;
  status: BuildStatus;
  /** Progress 0–100 if available */
  progress?: number;
  /** Human-readable status message */
  message?: string;
  /** ISO timestamp of last update */
  updatedAt: string;
}

export interface Artifact {
  /** Platform this artifact is for */
  platform: Platform;
  /** Human-readable label (e.g. "Android APK (release)") */
  label: string;
  /** Download URL */
  url: string;
  /** File size in bytes if known */
  sizeBytes?: number;
  /** MIME type */
  mimeType: string;
  /** ISO timestamp when artifact was produced */
  createdAt: string;
}

export interface LogChunk {
  timestamp: string;
  level: 'info' | 'warn' | 'error';
  message: string;
}

/**
 * The pluggable provider interface. Every build service adapter must
 * implement all five methods. The pipeline never imports a concrete
 * provider directly — it always goes through the registry.
 */
export interface BuildProvider {
  /** Unique identifier used in API requests and stored in the DB */
  readonly name: string;
  /** Human-readable display name */
  readonly displayName: string;
  /** Which platforms this provider can build */
  readonly supportedPlatforms: ReadonlyArray<Platform>;
  /** Whether this provider requires external API credentials */
  readonly requiresCredentials: boolean;
  /** Short description shown in the UI */
  readonly description: string;

  /**
   * Submit a new build job to this provider.
   * Must return a BuildJob with an externalId the provider assigned.
   */
  submitBuild(manifest: FileManifest, config: BuildConfig): Promise<BuildJob>;

  /**
   * Poll the current status of a previously submitted job.
   */
  getStatus(externalId: string, jobId: string): Promise<BuildStatusResult>;

  /**
   * Return download URLs for completed build artifacts.
   * Returns an empty array if the build hasn't finished yet.
   */
  getArtifacts(externalId: string, jobId: string): Promise<Artifact[]>;

  /**
   * Async generator that yields log chunks for a running or completed job.
   * Implementations may poll, stream, or return a static snapshot.
   */
  getLogs(externalId: string, jobId: string): AsyncGenerator<LogChunk>;
}
